# Generated by Django 6.0.2 on 2026-04-08 09:28

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.CharField(max_length=255)),
                ('target_ip', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.CharField(max_length=15)),
                ('dst_ip', models.CharField(max_length=15)),
                ('src_port', models.IntegerField()),
                ('dst_port', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('duration', models.FloatField()),
                ('packet_count', models.IntegerField()),
                ('byte_count', models.IntegerField()),
                ('bytes_per_packet', models.FloatField()),
                ('packets_per_sec', models.FloatField()),
                ('syn_count', models.IntegerField()),
                ('ack_count', models.IntegerField()),
                ('fin_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.db.models.functions.datetime.Now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('source_ip', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('traffic_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.trafficlog')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
